[project]
name = "easy-workflow-layout"
description = "a ComfyUI extension to organize workflow nodes into a clean, flowchart-like layout with same-type nodes aligned and connected nodes flowing left-to-right"
version = "0.1.0"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = ["Operating System :: OS Independent"]

[project.urls]
Repository = "https://github.com/aeslampanah/ComfyUI-Easy-Workflow-Layout"

[tool.comfy]
PublisherId = "aeslampanah"
DisplayName = "Easy Workflow Layout"
Icon = ""
requires-comfyui = ">=0.12.3" 
